### PR TITLE
Avoid crashing if host_name cannot be resolved

### PR DESCRIPTION
**Pull request by philippneugebauer**
Restarts the process if the host_name cannot be resolved instead of crashing the application

### CODE REVIEW

**Comment by philippneugebauer** [comment]
@jschniper any thoughts on merging this?

**Comment by jschniper** [comment]
I'll try to go through everything this week. There was another pull request that addressed a similar issue (https://github.com/jschniper/gelf_logger/pull/8) so I just want to make sure everything is clean.

**Comment by philippneugebauer** [comment]
This is my colleague but even that didn't fix our issue ;)

**Comment by jschniper** [comment]
That makes sense. I think it would delay the crash but the logger itself would go down when the DNS lookup fails. I'll try to go through everything tomorrow and get it merged.

Thank you!

**Comment by jschniper** [comment]
I went through the code and I was wrong about what I expected to occur. The hostname is passed directly to `:gen_udp.send` now, so the lookup occurs at the time the message is actually sent. Since the return value isn't checked it looks as though the logger would silently drop messages to a domain it can't resolve, which is a problem in its own right but doesn't explain the crash you are experiencing.

If you don't mind, can you attach some output from the crash so I can take a look and better understand what is going on.

**Comment by philippneugebauer** [comment]
I can't even start the application when the hostname cannot be resolved. It just crashes instantly. I will provide you the error message

**Comment by philippneugebauer** [comment]
So far I couldn't let it crash anymore, but maybe I just don't remember the setup anymore. I don't stop testing :P

**Comment by jschniper** [comment]
I've tried a few different things to recreate the crash and I haven't been able to so far. If you come across anything, please let me know.

**Comment by philippneugebauer** [comment]
I close it. If I ever stumple over it again, I will just reopen it.

**Pull request closed without merging**
